export const BARANGAYS = [
  'Poblacion',
  'Guyong',
  'Caypombo',
  'Santa Clara',
  'San Jose Patag',
  'Bagbaguin',
  'Pulong Buhangin',
  'Lalakhan',
  'Catmon',
  'Sta. Cruz',
]

export const JOB_CATEGORIES = [
  'Professional',
  'Skilled Labor',
  'Student Programs',
]

export const JOB_TYPES = ['Full-time', 'TUPAD', 'SPES', 'GIP', 'Contract']

export const INDUSTRIES = [
  'Manufacturing',
  'Retail & Trading',
  'Food & Hospitality',
  'Healthcare',
  'Construction',
  'Transportation & Logistics',
  'Technology & Services',
  'Agriculture',
  'Education',
  'Other',
]

export const ADMIN_DATA = {
  id: 1,
  role: 'admin',
  email: 'admin@joblinked.gov',
  full_name: 'JobLinked System Admin',
}

export const DEMO_SESSION_MAP = {
  applicant: { role: 'applicant', id: 1 },
  employer: { role: 'employer', id: 1 },
  admin: { role: 'admin', id: 1 },
}

export const APPLICANTS_DATA = [
  {
    id: 1,
    role: 'applicant',
    email: 'user@demo.com',
    password: 'demo123',
    full_name: 'John Applicant',
    phone: '09123456789',
    barangay: 'Poblacion',
    created_at: '2024-01-10',
  },
  {
    id: 2,
    role: 'applicant',
    email: 'maria.santos@demo.com',
    password: 'demo123',
    full_name: 'Maria Santos',
    phone: '09194561234',
    barangay: 'Caypombo',
    created_at: '2024-01-22',
  },
  {
    id: 3,
    role: 'applicant',
    email: 'joel.reyes@demo.com',
    password: 'demo123',
    full_name: 'Joel Reyes',
    phone: '09181239876',
    barangay: 'Santa Clara',
    created_at: '2024-02-04',
  },
]

export const EMPLOYERS_DATA = [
  {
    id: 1,
    role: 'employer',
    email: 'employer@demo.com',
    password: 'demo123',
    company_name: 'Santa Maria Builders Corp.',
    address: 'Poblacion, Sta. Maria',
    industry: 'Construction',
    contact_person: 'John Doe',
    business_permit: 'SMBC-001-2024',
    status: 'approved',
    created_at: '2024-01-15',
  },
  {
    id: 2,
    role: 'employer',
    email: 'waltermart@demo.com',
    password: 'demo123',
    company_name: 'WalterMart Sta. Maria',
    address: 'Caypombo, Sta. Maria',
    industry: 'Retail & Trading',
    contact_person: 'Jane Smith',
    business_permit: 'WM-204-2024',
    status: 'approved',
    created_at: '2024-02-01',
  },
  {
    id: 3,
    role: 'employer',
    email: 'joblinked.office@demo.com',
    password: 'demo123',
    company_name: 'JobLinked Sta. Maria',
    address: 'Municipal Hall, Poblacion, Sta. Maria',
    industry: 'Other',
    contact_person: 'Rosa Mendoza',
    business_permit: 'LGU-118-2024',
    status: 'approved',
    created_at: '2024-02-05',
  },
  {
    id: 4,
    role: 'employer',
    email: 'logistics@demo.com',
    password: 'demo123',
    company_name: 'Santa Clara Logistics Hub',
    address: 'Santa Clara, Sta. Maria',
    industry: 'Transportation & Logistics',
    contact_person: 'Carlo Reyes',
    business_permit: 'SCL-332-2024',
    status: 'approved',
    created_at: '2024-02-12',
  },
  {
    id: 5,
    role: 'employer',
    email: 'industrial.park@demo.com',
    password: 'demo123',
    company_name: 'Sta. Maria Industrial Park',
    address: 'Pulong Buhangin, Sta. Maria',
    industry: 'Manufacturing',
    contact_person: 'Elena Garcia',
    business_permit: 'SMIP-091-2024',
    status: 'approved',
    created_at: '2024-02-18',
  },
  {
    id: 6,
    role: 'employer',
    email: 'earthmovers@demo.com',
    password: 'demo123',
    company_name: 'Bulacan Earthmovers Inc.',
    address: 'San Jose Patag, Sta. Maria',
    industry: 'Construction',
    contact_person: 'Miguel Alvarez',
    business_permit: 'BEI-778-2024',
    status: 'pending',
    created_at: '2024-03-01',
  },
]

export const JOBS_DATA = [
  {
    id: 1,
    employer_id: 1,
    title: 'Civil Engineer',
    company: 'Santa Maria Builders Corp.',
    location: 'Poblacion, Sta. Maria',
    type: 'Full-time',
    category: 'Professional',
    salary: 'PHP 30,000 - 45,000',
    description:
      'Join our core team for upcoming municipal and commercial projects in Sta. Maria.',
    requirements: 'BS Civil Engineering, Licensed, 2+ years experience',
    status: 'active',
    created_at: '2024-02-10',
  },
  {
    id: 2,
    employer_id: 1,
    title: 'Skilled Mason',
    company: 'Santa Maria Builders Corp.',
    location: 'Guyong, Sta. Maria',
    type: 'Contract',
    category: 'Skilled Labor',
    salary: 'PHP 600 - 800 / day',
    description: 'Experienced masons needed for residential development projects.',
    requirements: 'TESDA NC II Certified, Physical fitness, 1+ year experience',
    status: 'active',
    created_at: '2024-02-12',
  },
  {
    id: 3,
    employer_id: 1,
    title: 'Heavy Equipment Operator',
    company: 'Santa Maria Builders Corp.',
    location: 'San Jose Patag, Sta. Maria',
    type: 'Full-time',
    category: 'Skilled Labor',
    salary: 'PHP 18,000 - 25,000',
    description: 'Operate bulldozers and loaders for ongoing infrastructure work.',
    requirements: "Professional driver's license, TESDA certificate, Safety training",
    status: 'active',
    created_at: '2024-02-14',
  },
  {
    id: 4,
    employer_id: 2,
    title: 'Customer Service Associate',
    company: 'WalterMart Sta. Maria',
    location: 'Caypombo, Sta. Maria',
    type: 'Full-time',
    category: 'Professional',
    salary: 'PHP 14,000 - 16,000',
    description: 'Help provide excellent service to local shoppers.',
    requirements: 'HS Graduate, Good communication skills, Weekend availability',
    status: 'active',
    created_at: '2024-02-16',
  },
  {
    id: 5,
    employer_id: 2,
    title: 'Inventory Accountant',
    company: 'WalterMart Sta. Maria',
    location: 'Caypombo, Sta. Maria',
    type: 'Full-time',
    category: 'Professional',
    salary: 'PHP 25,000 - 35,000',
    description: 'Manage daily inventory reconciliation and store reporting.',
    requirements: 'Accountancy graduate, Excel proficiency, Retail experience preferred',
    status: 'active',
    created_at: '2024-02-18',
  },
  {
    id: 6,
    employer_id: 3,
    title: 'Summer Intern (GIP)',
    company: 'Municipal Hall - Sta. Maria',
    location: 'Poblacion, Sta. Maria',
    type: 'GIP',
    category: 'Student Programs',
    salary: 'Minimum Wage',
    description: 'Government Internship Program for students residing in Sta. Maria.',
    requirements: 'Student or graduate, Resident of Sta. Maria, Resume submission',
    status: 'active',
    created_at: '2024-02-20',
  },
  {
    id: 7,
    employer_id: 3,
    title: 'SPES Participant',
    company: 'JobLinked Sta. Maria',
    location: 'Poblacion, Sta. Maria',
    type: 'SPES',
    category: 'Student Programs',
    salary: 'Allowance based',
    description: 'Special Program for Employment of Students during summer break.',
    requirements: 'Strictly for students, Low-income family status, School certification',
    status: 'active',
    created_at: '2024-02-22',
  },
  {
    id: 8,
    employer_id: 3,
    title: 'TUPAD Community Worker',
    company: 'DOLE / JobLinked Sta. Maria',
    location: 'Various Barangays, Sta. Maria',
    type: 'TUPAD',
    category: 'Skilled Labor',
    salary: 'Daily rate for 10 days',
    description: 'Emergency employment for displaced workers.',
    requirements: 'Sta. Maria resident, Unemployed or displaced, Valid barangay clearance',
    status: 'active',
    created_at: '2024-02-24',
  },
  {
    id: 9,
    employer_id: 4,
    title: 'Warehouse Worker',
    company: 'Santa Clara Logistics Hub',
    location: 'Santa Clara, Sta. Maria',
    type: 'Full-time',
    category: 'Skilled Labor',
    salary: 'PHP 12,000 - 14,000',
    description: 'Handle, sort, and move warehouse inventory safely and efficiently.',
    requirements: 'Can lift heavy loads, Reliable attendance, Forklift experience preferred',
    status: 'active',
    created_at: '2024-02-26',
  },
  {
    id: 10,
    employer_id: 5,
    title: 'Production Operator',
    company: 'Sta. Maria Industrial Park',
    location: 'Pulong Buhangin, Sta. Maria',
    type: 'Full-time',
    category: 'Skilled Labor',
    salary: 'PHP 15,000 - 18,000',
    description: 'Shift-based manufacturing work in electronics assembly.',
    requirements: 'HS Graduate, Willing to work on shifts, Basic machine handling',
    status: 'active',
    created_at: '2024-03-01',
  },
]

export const APPLICATIONS_DATA = [
  {
    id: 1,
    job_id: 1,
    user_id: 1,
    status: 'pending',
    applied_at: '2024-03-02',
  },
  {
    id: 2,
    job_id: 2,
    user_id: 2,
    status: 'accepted',
    applied_at: '2024-03-03',
  },
  {
    id: 3,
    job_id: 4,
    user_id: 3,
    status: 'rejected',
    applied_at: '2024-03-04',
  },
  {
    id: 4,
    job_id: 6,
    user_id: 1,
    status: 'pending',
    applied_at: '2024-03-06',
  },
  {
    id: 5,
    job_id: 9,
    user_id: 2,
    status: 'accepted',
    applied_at: '2024-03-07',
  },
]
