export const JOBS_DATA = [
  {
    id: 1,
    title: "Civil Engineer",
    company: "Santa Maria Builders Corp.",
    location: "Poblacion, Sta. Maria",
    type: "Full-time",
    category: "Professional",
    salary: "₱30,000 - ₱45,000",
    description:
      "Join our core team for upcoming municipal projects in Sta. Maria.",
    requirements: ["BS Civil Engineering", "Licensed", "2+ years experience"],
  },
  {
    id: 2,
    title: "Skilled Mason",
    company: "Guyong Construction Services",
    location: "Guyong, Sta. Maria",
    type: "Contract",
    category: "Skilled Labor",
    salary: "₱600 - ₱800 / day",
    description: "Experienced masons needed for residential developments.",
    requirements: ["TESDA NC II Certified", "Physical fitness"],
  },
  {
    id: 3,
    title: "Summer Intern (GIP)",
    company: "Municipal Hall - Sta. Maria",
    location: "Poblacion, Sta. Maria",
    type: "GIP",
    category: "Student Programs",
    salary: "Minimum Wage",
    description:
      "Government Internship Program for students residing in Sta. Maria.",
    requirements: ["Student/Graduate", "Resident of Sta. Maria"],
  },
  {
    id: 4,
    title: "Customer Service Associate",
    company: "WalterMart Sta. Maria",
    location: "Caypombo, Sta. Maria",
    type: "Full-time",
    category: "Professional",
    salary: "₱14,000 - ₱16,000",
    description: "Help provide excellent service to local shoppers.",
    requirements: ["HS Graduate", "Good communication skills"],
  },
  {
    id: 5,
    title: "Warehouse Worker",
    company: "Santa Clara Logistics Hub",
    location: "Santa Clara, Sta. Maria",
    type: "Full-time",
    category: "Skilled Labor",
    salary: "₱12,000 - ₱14,000",
    description: "Efficiently handle and organize local inventory.",
    requirements: ["Can lift heavy loads", "Reliable"],
  },
  {
    id: 6,
    title: "SPES Participant",
    company: "JobLinked Sta. Maria",
    location: "Poblacion, Sta. Maria",
    type: "SPES",
    category: "Student Programs",
    salary: "Allowance based",
    description:
      "Special Program for Employment of Students during summer break.",
    requirements: ["Strictly for students", "Low-income family status"],
  },
  {
    id: 7,
    title: "Heavy Equipment Operator",
    company: "Bulacan Earthmovers Inc.",
    location: "San Jose Patag, Sta. Maria",
    type: "Full-time",
    category: "Skilled Labor",
    salary: "₱18,000 - ₱25,000",
    description: "Experienced JCB and Bulldozer operators needed.",
    requirements: ["Professional Driver's License", "TESDA Cert"],
  },
  {
    id: 8,
    title: "Accountant",
    company: "L.M. Santiago Real Estate",
    location: "Bagbaguin, Sta. Maria",
    type: "Full-time",
    category: "Professional",
    salary: "₱25,000 - ₱35,000",
    description: "Manage financial records for local property developments.",
    requirements: ["CPA preferred", "Proficient in Excel"],
  },
  {
    id: 9,
    title: "TUPAD Community Worker",
    company: "DOLE / JobLinked Sta. Maria",
    location: "Various Barangays, Sta. Maria",
    type: "TUPAD",
    category: "Skilled Labor",
    salary: "Daily Rate (10 days)",
    description: "Emergency employment for displaced workers.",
    requirements: ["Sta. Maria Resident", "Unemployed/Displaced"],
  },
  {
    id: 10,
    title: "Production Operator",
    company: "Sta. Maria Industrial Park",
    location: "Pulong Buhangin, Sta. Maria",
    type: "Full-time",
    category: "Skilled Labor",
    salary: "₱15,000 - ₱18,000",
    description: "Shift-based manufacturing work in electronics assembly.",
    requirements: ["HS Graduate", "Willing to work on shifts"],
  },
];

export const BARANGAYS = [
  "Poblacion",
  "Guyong",
  "Caypombo",
  "Santa Clara",
  "San Jose Patag",
  "Bagbaguin",
  "Pulong Buhangin",
  "Lalakhan",
  "Catmon",
  "Sta. Cruz",
];

export const JOB_CATEGORIES = [
  "Professional",
  "Skilled Labor",
  "Student Programs",
];
export const JOB_TYPES = ["Full-time", "TUPAD", "SPES", "GIP", "Contract"];

export const INDUSTRIES = [
  'Manufacturing',
  'Retail & Trading',
  'Food & Hospitality',
  'Healthcare',
  'Construction',
  'Transportation & Logistics',
  'Technology & Services',
  'Agriculture',
  'Education',
  'Other'
];
